# Use config map for not-secret configuration data
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-configmap
data:
  AUTH_SECRET: "SUPERSECRET"
  KEYCLOAK_CLIENT_ID: "CLIENT_ID"
  KEYCLOAK_CLIENT_SECRET: "SUPERSECRET"
  KEYCLOAK_ISSUER_URL: "https://keycloak.local/realms/REALM"
  KUBERNETES_SERVER_URL: "https://IP:PORT"
  LOADBALANCER_IP: "IP"
  KUBERNETES_CA_Path: "/certs/ca.crt"
  NEXTAUTH_URL: "https://IP:PORT"
  NEXTAUTH_URL_INTERNAL: "https://IP:PORT"
  PRIVATE_KEY: "/certs/key.pem"
  CERTIFICATE: "/certs/cert.pem"
  ALLOW_UNTRUSTED_CERTS: "true"
  AUTH_TRUST_HOST: "true"
  PORT: "80"
  SSLPORT: "443"