apiVersion: kubelab.kubelab.local/v1
kind: Classroom
metadata:
  annotations:
    nfs.io/storage-path: class
  name: java-classroom
spec:
  templateContainer: "floreitz/kubelab-base:latest"
  allowUserRoot: "true"
  rootPass: "toor"
  teacher:
    spec:
      id: "t01"
  enrolledStudents:
    - spec:
        id: "575103"
---
apiVersion: kubelab.kubelab.local/v1
kind: Classroom
metadata:
  annotations:
    nfs.io/storage-path: class
  name: c-classroom
spec:
  allowUserRoot: "false"
  rootPass: "toor"
  templateContainer: "floreitz/kubelab-base:latest"
  teacher:
    spec:
      id: "t02"
  enrolledStudents:
    - spec:
        id: "575103"
---
apiVersion: kubelab.kubelab.local/v1
kind: Classroom
metadata:
  annotations:
    nfs.io/storage-path: class
  name: c-exam
spec:
  allowUserRoot: "false"
  rootPass: "toor"
  enableExamMode: "true"
  templateContainer: "floreitz/kubelab-base:latest"
  teacher:
    spec:
      id: "t01"
  enrolledStudents:
    - spec:
        id: "575103"