---
- hosts: master
  remote_user: "{{ user }}"
  gather_facts: false
  tasks:
    - name: Get user custom resources
      kubernetes.core.k8s_info:
        api_version: kubelab.kubelab.local/v1
        kind: KubelabUser
      register: user_info

    - name: Extract user names
      set_fact:
        user_info_list: >-
          {{
            user_info_list | default([]) +
            [
              {
                'name': item.metadata.name,
              }
            ]
          }}
      loop: "{{ user_info.resources }}"
      no_log: true

    - name: Display user names
      debug:
        msg: "{{ user_info_list }}"