version: "3"
services:
  kubelab:
    image: floreitz/kubelab-web:latest
    container_name: kubelab
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    volumes:
      - user_data:/students
      - class_data:/classes
      - ./certs:/certs
    environment:
      AUTH_SECRET: ${AUTH_SECRET}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_ISSUER_URL: ${KEYCLOAK_ISSUER_URL}
      KUBERNETES_SERVER_URL: ${KUBERNETES_SERVER_URL}
      LOADBALANCER_IP: ${LOADBALANCER_IP}
      KUBERNETES_CA_Path: ${KUBERNETES_CA_Path}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_URL_INTERNAL: ${NEXTAUTH_URL_INTERNAL}
      PRIVATE_KEY: ${PRIVATE_KEY}
      CERTIFICATE: ${CERTIFICATE}
      # Needed if not vercel
      AUTH_TRUST_HOST: "true"
      # For development only
      ALLOW_UNTRUSTED_CERTS: "true"
volumes:
  user_data:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER_IP},nolock,soft,rw"
      device: ":/srv/kubernetes/student"
  class_data:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER_IP},nolock,soft,rw"
      device: ":/srv/kubernetes/class"
