---
- name: Create kubelab-system namespace
  k8s:
    name: kubelab-system
    api_version: v1
    kind: Namespace
    state: present  

- name: Copying manifest
  template:
    src: operator.yaml
    dest: /tmp/operator.yaml
    owner: flo
    group: flo
    mode: '0777'

- name: Create operator
  k8s:
    state: present   
    namespace: kubelab-system
    src: /tmp/operator.yaml